### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by brasileric** [Jyxon/GDPR-Cookie-Compliance#1]
Hi seems to be a great tool. Do you have an example to see it working on a website?

Thx

**Comment by mfrankruijter** [comment]
Hi there,

Thanks for you interest and suggestion. I could setup an example later today :). I'll update this issue when it's ready.

**Comment by brasileric** [comment]
Hi,
Well I can try it by myself as well of course. But I thought if you implemented already on a live website, I could see it there :)

**Comment by mfrankruijter** [comment]
I've just created a small example page 😄 
You can check it out here: [https://gdpr-cookie-example.jyxon.com/](https://gdpr-cookie-example.jyxon.com/).

If you have anymore questions, suggestions or ideas, let me know.

**Comment by frontEndExpert** [comment]
how can one use the code without se4ver side php?
can we simply check the cookie on the front end side with javascript?

**Comment by mfrankruijter** [comment]
Hello there,

Yes you can. Please check https://github.com/Jyxon/GDPR-Cookie-Compliance#gdpr_cookiejs in the manual on how to do this.

**Comment by malutanpetronel** [comment]
Hi and thank you for creating this tool.
If I would like to check directly in some js file if I can set or I should delete the cookie, I should manually iterate all gdpr_cookie_bar_option_functional... gdpr_cookie_bar_option_ga or _whatever and see if the checkbox is checked in order to follow the user preferences regarding some scopes?
