### ISSUE TITLE
Functional and Analytical cookies

### ISSUE THREAD

**Issue by webprogrammierer** [Jyxon/GDPR-Cookie-Compliance#2]
What is the exact difference between these two types of cookies?

What about cookies from:
- Ebay Partnernetwork
- Amazon Partnernet
- Google Adsense
- Youtube Videos
- Amazon Pay
- Affili.net or other affiliate networks
- and Google Analytics

How does the script recognize all these mentioned cookies? And the script disables all of them, if the user uncheckes the "Analytical cookies" checkbox?

How to config to let the website visitor disable only one out of the list or this disable individually?

**Comment by mfrankruijter** [comment]
Hello there,

Thanks for your interest in this package. The package is build in a way that you can completely configure it to your needs. The default setup defines 2 "scopes", namely "functional" and "analytical" cookies. The difference between these 2 is that "functional" cookies are required for a correctly functioning website, for example tracking if you jave shown the cookie bar or not (which is built into the package). Analytical cookies are for tracking purposes of your users. These cookies could be used to uniquely identify a user (even if it's a randomized string). For the latter, confirmation is required before they can be set.

Going back to my first point about configuration. You can define additional said "scopes" in the configuration file (just make a copy of the analytical data block and change the values to your needs). If you wish to put these into new scopes ofcourse. Then you can make the calls to the functions from the documentation with your own defined scope key as the first parameter.

About third party extensions. If you have control over these cookie setters directly (you are for example using the setcookie function in your PHP script). Then you should replace these with the documented setCookie function. If you don't have direct control over these functions, you should consult the documentation of the third party extensions you are using. I know that Google Analytics for example has a dedicated part in their implementation guide about setting cookies (adding a GET parameter to the JavaScript URL). To check for the user if you should add this flag, you can use the canSet function. So `'some-url.test/google-tracker-code' . ($manager->canSet('analytical') ?: '?no-cookie=1');` would be an example of how to check if setting a cookie by a third party is allowed.

I hope this information helps you.

If you have any more questions, please let me know.

**Comment by webprogrammierer** [comment]
I want to opt-in or opt-out from those cookies mentioned above.

Please provide an example how to configure in order to let the visitor opt-out from Amazon Partnernet cookies.

**Comment by mfrankruijter** [comment]
If you want to add an additional scope, simply do so in your JSON configuration with an entry like this:
```  
{
    "scope": "thid_party_scope_name",
    "required": 0,
    "title": "Some third party title",
    "description": "Some description for your cookies"
}
```

Then you can (from a PHP standpoint) use the function `$manager->canSet('thid_party_scope_name');` to implement a check wether the cookie can be set or not. For the implementation of those third party cookies I'd like to refer you to their respective implementation guides. These will most likely contain a usage guide of how the implementation per party works. If you're talking about referral links, you have 2 options if you are not setting any cookies yourself or implementing third party code that sets a cookie for you, but are referring to another website.

1. You can trust that they will have to implement a similar solution (because they are setting the cookie on their domain, so it's technically not your problem at that moment).
2. You can strip the referral code (example: `?ref=some_code_for_referrals`) from the URL, in a similar fashion as I described in my last example for Google tracking.

**Comment by jimbobger** [comment]
Hi Pulsebear,

sorry for the double posting, but a specific example with Google analytics Code would be extremply helpful.

Thank you

Greetings 
Jimbob
