### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jimbobger** [Jyxon/GDPR-Cookie-Compliance#3]
Hi Jyxon,

thank you very much for creating this wonderful piece of software.
As I'm a newbie I'm uncertain how to implement f.e. the Google Analytics script in this section

$manager->setCookie('functional', 'functional_cookie_name', 'some-non-tracking-value', time() + 3600, '/', '*.mydomain.com', 1);
$manager->setCookie('analytical', 'tracking_cookie_name', 'uniquely-identifiable-information', time() + 360000, '/', '*.mydomain.com', 1);

Is it possible for you to create a specific example how to do this?

With kind regards
Jimbob

**Comment by mfrankruijter** [comment]
Hi there Jimbob,

Thank you for you interest in the package.

In order to intercept your Google Analytics from setting cookies en sending data to their server (only if a user has given you consent), you can do the following.

The `XXXXXX-Y` part should be the Tracking ID you have gotten from Google Analytics. This can be found in the dashboard of https://analytics.google.com

An example implementation of Google Analytics would be as follows:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXX-Y"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXX-Y');
</script>
```
In this example the tracking would just be done without consent.
In the manual of Google Analytics, the following entry can be found https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out

Which states that in order to disable cookies being set and data being shared with the Google Services, you can set a flag in your DOM.  This can be done in a `<script>` tag in your Template (which I imagine in this case is being parsed by PHP.

The flag would be:
```
<script>
window['ga-disable-UA-XXXXX-Y'] = true;
</script>
```

With the package installed and in your template (where you define you Google Analytics tag you should do the following:
```
<?php if (!$manager->canSet('analytical')): ?>
    <script>
        window['ga-disable-UA-XXXXX-Y'] = true;
    </script>
<?php endif; ?>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXX-Y"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXX-Y');
</script>
```

For this I assumed the following:
- You used the default settings that came with the package.
- You have followed the other instructions to setup the `$manager` variable which is used numerous times in the guide.

I hope this helps you out in your implementation.

Kind regards,

Marcel

**Comment by jimbobger** [comment]
Hi Pulse,

thank you so much for your extensive explanation.

With kind regards
Jimbob
