### ISSUE TITLE
Google Analytics Cookie

### ISSUE THREAD

**Issue by velkony** [Jyxon/GDPR-Cookie-Compliance#4]
Hello,
I do not understand how exactly I can use this library for Google Analytics.
If the user does't accept the cookiesр, does that mean it will not be loaded GA script?

```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'XX-XXXXXXXX-X', 'example.com');
ga('send', 'pageview');
</script>
```
Where should I add the settings of GA?

Best Regards

**Comment by mfrankruijter** [comment]
Hi there @velkony 

Thank you for interest in the package.

In a previous issue I have addressed an implementation for Google Analytics. 
Which was as followed (I adjusted the example to use the standard analytics implementation as you requested, but in the end does the same):

In order to intercept your Google Analytics from setting cookies en sending data to their server (only if a user has given you consent), you can do the following.

The `XXXXXX-Y` part should be the Tracking ID you have gotten from Google Analytics. This can be found in the dashboard of https://analytics.google.com

An example implementation of Google Analytics would be as follows:
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-XXXXXX-Y', 'example.com');
ga('send', 'pageview');
</script>
```
In this example the tracking would just be done without consent.
In the manual of Google Analytics, the following entry can be found https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out

Which states that in order to disable cookies being set and data being shared with the Google Services, you can set a flag in your DOM.  This can be done in a `<script>` tag in your Template (which I imagine in this case is being parsed by PHP.

The flag would be:
```
<script>
window['ga-disable-UA-XXXXX-Y'] = true;
</script>
```

With the package installed and in your template (where you define you Google Analytics tag you should do the following:
```
<?php if (!$manager->canSet('analytical')): ?>
    <script>
        window['ga-disable-UA-XXXXX-Y'] = true;
    </script>
<?php endif; ?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-XXXXXX-Y', 'example.com');
ga('send', 'pageview');
</script>
```

For this I assumed the following:
- You used the default settings that came with the package.
- You have followed the other instructions to setup the `$manager` variable which is used numerous times in the guide.

In this implementation the tracking is completely blocked off from Google Analytics.
You can also choose to anonymize the IP-address as follows:
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
<?php if (!$manager->canSet('analytical')): ?>
    ga('set', 'anonymizeIp', true);
<?php endif; ?>
  ga('create', 'UA-XXXXXX-Y', 'example.com');
  ga('send', 'pageview');
</script>
``` 
This implementation will still set a cookie (which needs consent), and creates the ability to track anonymized data on your website. You could for example add an additional option, to request a different approach on tracking. A pretty global description of it's effects could be:
```
analytical = yes
anonymized-analytical = yes
```
Would result in full analytics.

```
analytical = no
anonymized-analytical = yes
```
Would result in adding the anonymized IP address flag.

```
analytical = no
anonymized-analytical = no
```
Would result in disabling analytics.

The code could look something like this:
```
<?php if (!$manager->canSet('analytical') && !$manager->canSet('anonymized-analytical')): ?>
    <script>
        window['ga-disable-UA-XXXXX-Y'] = true;
    </script>
<?php endif; ?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-XXXXXX-Y', 'example.com');
<?php if (!$manager->canSet('analytical') && $manager->canSet('anonymized-analytical')): ?>
    ga('set', 'anonymizeIp', true);
<?php endif; ?>
ga('send', 'pageview');
</script>
```

If you require any more help, don't hesitate to ask. 🙂 

I hope this helps you out in your implementation.

Kind regards,

Marcel
